# Generated by Django 5.2 on 2025-05-23 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almacenes', '0001_initial'),
        ('productos', '0003_producto_almacen'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('tipo_movimiento', models.CharField(choices=[('compra', 'Compra'), ('venta', 'Venta'), ('ajuste', 'Ajuste Manual')], max_length=10)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('almacen_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_destino', to='almacenes.almacen')),
                ('almacen_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_origen', to='almacenes.almacen')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
        ),
    ]
