# Generated by Django 5.2 on 2025-05-12 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacenes', '0001_initial'),
        ('productos', '0002_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='almacen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='almacenes.almacen'),
        ),
    ]
