# Generated by Django 5.2 on 2025-05-20 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('correo', models.EmailField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
                ('calificacion', models.IntegerField(blank=True, max_length=2, null=True)),
            ],
        ),
    ]
